const fraseElement = document.querySelector("#fraseElement")
const reflexaoElement = document.querySelector("#reflexaoElement")
const buttonRevelar = document.querySelector("#buttonRevelar")
const frases = [
"O segredo não é o sucesso, mas o caminho para chegar a ele.",
"Lembre-se de onde você veio, e que você não chegou aqui por acaso.",
"Você quer ganhar dinheiro ou receber salário?",
"Não sonhe com sucesso, trabalhe por ele",
"Se você não consegue vencer o despertador ao amanhecer, imagine alcançar seus objetivos",
"Acorde antes que todos, faça o que muitos não fazem, e conquiste o que ninguém vai conquistar!",
"Se você gasta dinheiro comprando o que não precisa, breve terá que vender as coisas que precisa para conseguir dinheiro.",
"Acredite em si mesmo.",
"Você é do tamanho dos seus sonhos, principalmente das suas conquistas.",
"Quem não levanta e para ascender a luz, não tem direito de reclamar do escuro.",
"Não pare quando estiver cansado, só pare quando estiver acabado",
"Não é fácil vencer a quem nunca se rende.",
"Quem faz o que todo mundo faz, colhe o que todo mundo colhe",
"Se está tudo indo bem demais, desconfie, toda busca tem um preço a ser pago!",
"Você não pode vencer a guerra contra o mundo, se não vencer sua guerra interior primeiro.",
"Todos querem ir para o céu, mas não querem morrer...",
"Aos outros dou o direito de serem como são, a mim o dever de ser melhor a cada dia.",
"Se sua disciplina e dedicação forem maior que suas distrações, você chegará muito mais longe que os “talentosos” que não sabem de onde vem e para onde vão.",
"A luta não termina quando sentir cansaço, mas sim quando atingir o sucesso.",
"Onde você está é o resultado de quem você era, mas pra onde você vai depende inteiramente de quem você escolhe ser a partir deste momento ",
"Quem você quer se tornar é muito mais importante do que oque você está fazendo, mas é o que você esta fazendo que determina em quem você está se tornando.",
"Hoje é o dia mais importante da sua vida! O que você faz hoje é que determina quem você está se tornando.",
"Se você não dedicar tempo à exercicíos e bons hábitos, provavelmente precisará dedicar tempo para doenças e remediações.",
"Deus da grandes desafios à grandes pessoas.",
"Nao importa como foi o seu passado, o seu futuro depende exclusivamente de você, e agora.",
"Quando der vontade de chorar, chore, e faça o possível para não voltar à chorar novamente pelo mesmo motivo.",
"Quando a cabeça não pensa, o corpo padece.",
"Seu maior inimigo está dentro de você!",
"Não espere ninguém te dizer que você é capaz, acredite em você mesmo, seja seu maior incentivador.",
"Seja grato pelo que tem hoje mas nunca acomodado. 'Estabilidade não existe - Flávio Augusto' ",
"Se você não se destaca pelo talento, vença pelo esforço.",
"Ninguém segura alguém que quer mudar de vida!",
"Você erra 100% das vezes que você não tenta.",
"uma dificuldade é apenas um intervalo entre duas felicidades - Orochi",
"Enquanto você for uva vão te pisar, mas quando virar vinho, vão ter que te engolir.",
"A maior das riquezas é saber dar valor ao que realmente importa.",
"Dinheiro é como um reflexo no espelho; se você perde tempo correndo atras dele, ele vai estar sempre correndo de você também. Experimente se tornar o tipo de pessoa que atrai o dinheiro, e ele quem vai começar a correr atrás de você.",
"Tem gente que tem tudo e ao mesmo tempo não tem nada, porque não sabe o valor do que tem.",
"O erro é importante para te fazer aprender, mas ele não pode te tirar do jogo.",
"Tudo vem para ensinar. Se você não aprendeu, a aula ainda não acabou.",
"Existem duas formas de se aprender alguma coisa, quebrando a cara, ou aprendendo com quem já quebrou.",
"Você prefere morar na pior casa do bairro rico, ou na pior casa do bairro pobre?",
"Ser empregado de si mesmo não é empreender.",
"Não invista no que você não consegue explicar.",
"Se um cara me contrata para dar uma cambalhota, eu dou três.",
"Não critique o resultado, mas o processo.",
"Palavras ensinam, exemplos arrastam.",
"Pra quem só sabe usar o martelo, todo problema é um prego",
"Para Deus não existe passado, presente, futuro, pra ele é tudo a mesma coisa, então se Ele deixou um desejo arder no seu coração, é pq Ele já te deu, tome posse.",
"Eu não acho nada, ou eu sei ou não sei.",
"O que você aprendeu hoje?",
"Tem gente que é tão pobre que só tem dinheiro, tem gente que é tão feia que só tem beleza",
"A Cada dia menos perfeito e mais feliz.",
"Comemore o sucesso mas saiba que assim como o fracasso ele é passageiro.",
"A melhor forma de aprender é ensinando.",
"Critica de quem não construiu nada, não serve para nada.",
"Não se atreva a ensinar o que não sabe.",
"Eu não luto com minha espada e nem me defendo com meu escudo.",
"Multiplique sua semente e alimente a multidão.",
"A porta aberta é Você mas a fechada tbm é Você",
"O conhecimento nada tem a ver com a sabedoria.",
"Seu propósito pode estar escondido por trás da sua dor.",
"O mundo interno cria o mundo externo.",
"Enriquecer é uma questão de escolha. - Gustavo Cerbasi",
"Um homem não pode ser menor do que o dinheiro que ele possui.",
"O dinheiro que você ganha não tem a ver com o esforço que você faz, mas com o problema que você resolve.",
"O que fortalece meu filho não é minha herança, é o meu legado. - Deive Leonardo",
"Uma nova construção não é feita em cima de escombros.",
"Nem todo mundo pede ajuda, mas todo mundo precisa.",
"Você é do tamanho da sua fé.",
"Quanto melhor o seu argumento menor o volume da sua voz.",
"Intimidade da acesso.",
"Nem tudo que eu quero eu preciso, e nem tudo que preciso eu mereço.",
"Coloca o pé e Ele vai por o chão.",
"Fama e dinheiro resolvem problemas externos, não internos.",
"O que a gente chama de 'silêncio de Deus', Deus chama de falta de intimidade.",
"Você mente para pouca gente muito tempo e você mente para muita gente pouco tempo, mas você não mente para todo mundo o tempo todo.",
"Não é pq eu perdi que eu sou um derrotado, e não é porque eu venci que eu sou inderrotável.",
"É fácil desistir de um produto, é difícil desistir de um propósito.",
"Os homens se fazem de rei quando o rei se fez de plebeu.",
"Pensar é mover-se ao infinito. - Henri Lacordaire",
"No pior dia esteja vestido no seu rosto com o melhor sorriso.",
"Quem tem medo de errar, tem medo de aprender.",
"Tem vezes que meu silêncio vai falar por mim, tem vezes que até meu silêncio vai se aquietar.",
"Rede social é um palco, o 'behind the scenes' ninguém mostra.",
"As pessoas vão falar muitas coisas sobre você, mas poucos merecem uma explicação.",
"Sofrimento é temporário, desistir é pra sempre.",
"Não de para seus filhos o que você não teve, ensine a eles o que não te ensinaram.",
"Sozinho controle seus pensamentos, em familia e amigos controle sua tolerância, e em sociedade controle sua língua. - Felipe Titto",
"O homem é de fato o que ele acredita que é.",
"Todo mundo tem um vazio do tamanho de Deus.",
"A gente não sabe nossa verdadeira força ate que ser forte seja nossa ultima opção.",
"Seu nível de sucesso raramente excederá seu nível de desenvolvimento pessoal. Porque o sucesso é atraído pela pessoa que você se torna.",
"Não negue seus sentimentos, esta tudo bem em chorar, estar assustado, mas não em desistir. Se permita sentir emoções e transforme-as em energia.",
"I love sun but the things don’t grow just with de sun, they need the rain. My greatest achievements don’t come from easy times, they come from hard times.",
"Excelência não é um ato, mas um hábito.",
"Deus não é do tamanho das nossas experiências.",
"Tudo que eu não gosto em você eu corrijo em mim.",
"A pessoa que você quer ser é contruida no 'dark room' da solitude.",
"Se não couber na sua mente, não vai caber na sua mão.",
"A dor tem como objetivo gerar movimento.",
"A realidade é um glorioso cemitério de sonhos. - Filipe Ret",
"Suas atitudes gritam tão alto que eu não consigo ouvir o que você está dizendo.",
"Nenhuma dor é maior que a capacidade de Deus de curar.",
"A constância dispensa exagero",
]
const reflexoes = [
"muitas pessoas acabam olhando para pessoas bem sucedidas em qualquer que for a área e acham que as imitando terão os mesmos resultados, mas a realidade é que o que levou essas pessoas aos seus lugares atuais não é o que elas estão fazendo hoje, mas o que elas fizeram até aqui; o treino e alimentação de um jogardor de futebol em formação e diferente de um jogador ja maduro, um precisa ganhar massa, resistência entre outras qualidaddes, enquanto outro precisa de ajustes finos; assim como um investidor bem sucedido, se você for se inpirar em seus estilo de vida e não tiver mutio dinheiro, rapidamente vai quebrar, indo em restaurantes caros, viagens, festas, adquirindo passivos e muito mais, mas a real é que esses investidores só podem se dar esse luxo porque tiveram exito em suas areas, mas não foi sempre assim, no caminho até o sucesso eles provavelmente não tinham acesso a esse estilo de vida, mas estavam focados em fazer seus negócios e investimentos darem certo. Então quando você olhar para alguém que admira, se pergunte oque ela fez para chegar até ali, e não o que ela faz hoje."
]



    const numeroAleatorio = Math.floor(Math.random() * frases.length)
    fraseElement.innerHTML = frases[numeroAleatorio]
    reflexaoElement.innerHTML = reflexoes[numeroAleatorio]
    buttonRevelar.setAttribute("disabled", true)
    
    setTimeout(function() {
        buttonRevelar.removeAttribute("disabled");
    }, 5000)